version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  docker_build:
    steps:
      run:
        name: Build docker image
        command: ls
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd db && yarn install
            - run: cd db && yarn build

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - docker_build:
        requires:
          - build-and-test
